// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cc1_levelset.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cc1LevelsetUtils {

  /// <summary>Holder for reflection information generated from cc1_levelset.proto</summary>
  public static partial class Cc1LevelsetReflection {

    #region Descriptor
    /// <summary>File descriptor for cc1_levelset.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Cc1LevelsetReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJjYzFfbGV2ZWxzZXQucHJvdG8SEmNjMV9sZXZlbHNldF91dGlscyKBAgoI",
            "TGV2ZWxzZXQSDAoEbmFtZRgBIAEoCRIpCgZsZXZlbHMYAiADKAsyGS5jYzFf",
            "bGV2ZWxzZXRfdXRpbHMuTGV2ZWwSMwoHc3RvcmllcxgDIAMoCzIiLmNjMV9s",
            "ZXZlbHNldF91dGlscy5MZXZlbHNldC5TdG9yeRqGAQoFU3RvcnkSFAoMbGV2",
            "ZWxfbnVtYmVyGAEgASgFEjUKBHR5cGUYAiABKA4yJy5jYzFfbGV2ZWxzZXRf",
            "dXRpbHMuTGV2ZWxzZXQuU3RvcnkuVHlwZRIMCgR0ZXh0GAMgAygJIiIKBFR5",
            "cGUSDAoIUFJPTE9HVUUQABIMCghFUElMT0dVRRABIvUDCgVMZXZlbBINCgV0",
            "aXRsZRgBIAEoCRIOCgZhdXRob3IYAiABKAkSDgoGbnVtYmVyGAMgASgFEgwK",
            "BHRpbWUYBCABKAUSDQoFY2hpcHMYBSABKAUSDAoEaGludBgGIAEoCRIQCghw",
            "YXNzd29yZBgHIAEoCRIvCgNtYXAYCCADKAsyIi5jYzFfbGV2ZWxzZXRfdXRp",
            "bHMuTGV2ZWwuTWFwRW50cnkSQgoNdHJhcF9jb250cm9scxgJIAMoCzIrLmNj",
            "MV9sZXZlbHNldF91dGlscy5MZXZlbC5UcmFwQ29udHJvbHNFbnRyeRJECg5j",
            "bG9uZV9jb250cm9scxgKIAMoCzIsLmNjMV9sZXZlbHNldF91dGlscy5MZXZl",
            "bC5DbG9uZUNvbnRyb2xzRW50cnkSEAoIbW92ZW1lbnQYCyADKAUaSAoITWFw",
            "RW50cnkSCwoDa2V5GAEgASgFEisKBXZhbHVlGAIgASgLMhwuY2MxX2xldmVs",
            "c2V0X3V0aWxzLlRpbGVTcGVjOgI4ARozChFUcmFwQ29udHJvbHNFbnRyeRIL",
            "CgNrZXkYASABKAUSDQoFdmFsdWUYAiABKAU6AjgBGjQKEkNsb25lQ29udHJv",
            "bHNFbnRyeRILCgNrZXkYASABKAUSDQoFdmFsdWUYAiABKAU6AjgBImkKCFRp",
            "bGVTcGVjEiwKA3RvcBgBIAEoDjIfLmNjMV9sZXZlbHNldF91dGlscy5DQzFU",
            "aWxlQ29kZRIvCgZib3R0b20YAiABKA4yHy5jYzFfbGV2ZWxzZXRfdXRpbHMu",
            "Q0MxVGlsZUNvZGUq4QwKC0NDMVRpbGVDb2RlEgkKBUZMT09SEAASCAoEV0FM",
            "TBABEggKBENISVAQAhIJCgVXQVRFUhADEggKBEZJUkUQBBIRCg1JTlZfV0FM",
            "TF9QRVJNEAUSCwoHUEFORUxfThAGEgsKB1BBTkVMX1cQBxILCgdQQU5FTF9T",
            "EAgSCwoHUEFORUxfRRAJEgkKBUJMT0NLEAoSCAoERElSVBALEgcKA0lDRRAM",
            "EgsKB0ZPUkNFX1MQDRIRCg1DTE9ORV9CTE9DS19OEA4SEQoNQ0xPTkVfQkxP",
            "Q0tfVxAPEhEKDUNMT05FX0JMT0NLX1MQEBIRCg1DTE9ORV9CTE9DS19FEBES",
            "CwoHRk9SQ0VfThASEgsKB0ZPUkNFX0UQExILCgdGT1JDRV9XEBQSCAoERVhJ",
            "VBAVEg0KCUJMVUVfRE9PUhAWEgwKCFJFRF9ET09SEBcSDgoKR1JFRU5fRE9P",
            "UhAYEg8KC1lFTExPV19ET09SEBkSCgoGSUNFX1NFEBoSCgoGSUNFX1NXEBsS",
            "CgoGSUNFX05XEBwSCgoGSUNFX05FEB0SEgoOQkxVRV9XQUxMX0ZBS0UQHhIS",
            "Cg5CTFVFX1dBTExfUkVBTBAfEg4KCk5PVF9VU0VEXzAQIBIJCgVUSElFRhAh",
            "EgoKBlNPQ0tFVBAiEhAKDEdSRUVOX0JVVFRPThAjEhAKDENMT05FX0JVVFRP",
            "ThAkEg8KC1RPR0dMRV9XQUxMECUSEAoMVE9HR0xFX0ZMT09SECYSDwoLVFJB",
            "UF9CVVRUT04QJxIPCgtUQU5LX0JVVFRPThAoEgwKCFRFTEVQT1JUECkSCAoE",
            "Qk9NQhAqEggKBFRSQVAQKxIQCgxJTlZfV0FMTF9BUFAQLBIKCgZHUkFWRUwQ",
            "LRIPCgtQT1BfVVBfV0FMTBAuEggKBEhJTlQQLxIMCghQQU5FTF9TRRAwEgoK",
            "BkNMT05FUhAxEhAKDEZPUkNFX1JBTkRPTRAyEg4KCkRST1dOX0NISVAQMxIQ",
            "CgxCVVJORURfQ0hJUDAQNBIQCgxCVVJORURfQ0hJUDEQNRIOCgpOT1RfVVNF",
            "RF8xEDYSDgoKTk9UX1VTRURfMhA3Eg4KCk5PVF9VU0VEXzMQOBINCglDSElQ",
            "X0VYSVQQORIRCg1VTlVTRURfRVhJVF8wEDoSEQoNVU5VU0VEX0VYSVRfMRA7",
            "EhMKD0NISVBfU1dJTU1JTkdfThA8EhMKD0NISVBfU1dJTU1JTkdfVxA9EhMK",
            "D0NISVBfU1dJTU1JTkdfUxA+EhMKD0NISVBfU1dJTU1JTkdfRRA/EgkKBUFO",
            "VF9OEEASCQoFQU5UX1cQQRIJCgVBTlRfUxBCEgkKBUFOVF9FEEMSDgoKRklS",
            "RUJBTExfThBEEg4KCkZJUkVCQUxMX1cQRRIOCgpGSVJFQkFMTF9TEEYSDgoK",
            "RklSRUJBTExfRRBHEgoKBkJBTExfThBIEgoKBkJBTExfVxBJEgoKBkJBTExf",
            "UxBKEgoKBkJBTExfRRBLEgoKBlRBTktfThBMEgoKBlRBTktfVxBNEgoKBlRB",
            "TktfUxBOEgoKBlRBTktfRRBPEgwKCEdMSURFUl9OEFASDAoIR0xJREVSX1cQ",
            "URIMCghHTElERVJfUxBSEgwKCEdMSURFUl9FEFMSCwoHVEVFVEhfThBUEgsK",
            "B1RFRVRIX1cQVRILCgdURUVUSF9TEFYSCwoHVEVFVEhfRRBXEgwKCFdBTEtF",
            "Ul9OEFgSDAoIV0FMS0VSX1cQWRIMCghXQUxLRVJfUxBaEgwKCFdBTEtFUl9F",
            "EFsSCgoGQkxPQl9OEFwSCgoGQkxPQl9XEF0SCgoGQkxPQl9TEF4SCgoGQkxP",
            "Ql9FEF8SEAoMUEFSQU1FQ0lVTV9OEGASEAoMUEFSQU1FQ0lVTV9XEGESEAoM",
            "UEFSQU1FQ0lVTV9TEGISEAoMUEFSQU1FQ0lVTV9FEGMSDAoIQkxVRV9LRVkQ",
            "ZBILCgdSRURfS0VZEGUSDQoJR1JFRU5fS0VZEGYSDgoKWUVMTE9XX0tFWRBn",
            "EgwKCEZMSVBQRVJTEGgSDgoKRklSRV9CT09UUxBpEgoKBlNLQVRFUxBqEhEK",
            "DVNVQ1RJT05fQk9PVFMQaxIMCghQTEFZRVJfThBsEgwKCFBMQVlFUl9XEG0S",
            "DAoIUExBWUVSX1MQbhIMCghQTEFZRVJfRRBvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Cc1LevelsetUtils.CC1TileCode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Cc1LevelsetUtils.Levelset), global::Cc1LevelsetUtils.Levelset.Parser, new[]{ "Name", "Levels", "Stories" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Cc1LevelsetUtils.Levelset.Types.Story), global::Cc1LevelsetUtils.Levelset.Types.Story.Parser, new[]{ "LevelNumber", "Type", "Text" }, null, new[]{ typeof(global::Cc1LevelsetUtils.Levelset.Types.Story.Types.Type) }, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Cc1LevelsetUtils.Level), global::Cc1LevelsetUtils.Level.Parser, new[]{ "Title", "Author", "Number", "Time", "Chips", "Hint", "Password", "Map", "TrapControls", "CloneControls", "Movement" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Cc1LevelsetUtils.TileSpec), global::Cc1LevelsetUtils.TileSpec.Parser, new[]{ "Top", "Bottom" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum CC1TileCode {
    [pbr::OriginalName("FLOOR")] Floor = 0,
    [pbr::OriginalName("WALL")] Wall = 1,
    [pbr::OriginalName("CHIP")] Chip = 2,
    [pbr::OriginalName("WATER")] Water = 3,
    [pbr::OriginalName("FIRE")] Fire = 4,
    [pbr::OriginalName("INV_WALL_PERM")] InvWallPerm = 5,
    [pbr::OriginalName("PANEL_N")] PanelN = 6,
    [pbr::OriginalName("PANEL_W")] PanelW = 7,
    [pbr::OriginalName("PANEL_S")] PanelS = 8,
    [pbr::OriginalName("PANEL_E")] PanelE = 9,
    [pbr::OriginalName("BLOCK")] Block = 10,
    [pbr::OriginalName("DIRT")] Dirt = 11,
    [pbr::OriginalName("ICE")] Ice = 12,
    [pbr::OriginalName("FORCE_S")] ForceS = 13,
    [pbr::OriginalName("CLONE_BLOCK_N")] CloneBlockN = 14,
    [pbr::OriginalName("CLONE_BLOCK_W")] CloneBlockW = 15,
    [pbr::OriginalName("CLONE_BLOCK_S")] CloneBlockS = 16,
    [pbr::OriginalName("CLONE_BLOCK_E")] CloneBlockE = 17,
    [pbr::OriginalName("FORCE_N")] ForceN = 18,
    [pbr::OriginalName("FORCE_E")] ForceE = 19,
    [pbr::OriginalName("FORCE_W")] ForceW = 20,
    [pbr::OriginalName("EXIT")] Exit = 21,
    [pbr::OriginalName("BLUE_DOOR")] BlueDoor = 22,
    [pbr::OriginalName("RED_DOOR")] RedDoor = 23,
    [pbr::OriginalName("GREEN_DOOR")] GreenDoor = 24,
    [pbr::OriginalName("YELLOW_DOOR")] YellowDoor = 25,
    [pbr::OriginalName("ICE_SE")] IceSe = 26,
    [pbr::OriginalName("ICE_SW")] IceSw = 27,
    [pbr::OriginalName("ICE_NW")] IceNw = 28,
    [pbr::OriginalName("ICE_NE")] IceNe = 29,
    [pbr::OriginalName("BLUE_WALL_FAKE")] BlueWallFake = 30,
    [pbr::OriginalName("BLUE_WALL_REAL")] BlueWallReal = 31,
    [pbr::OriginalName("NOT_USED_0")] NotUsed0 = 32,
    [pbr::OriginalName("THIEF")] Thief = 33,
    [pbr::OriginalName("SOCKET")] Socket = 34,
    [pbr::OriginalName("GREEN_BUTTON")] GreenButton = 35,
    [pbr::OriginalName("CLONE_BUTTON")] CloneButton = 36,
    [pbr::OriginalName("TOGGLE_WALL")] ToggleWall = 37,
    [pbr::OriginalName("TOGGLE_FLOOR")] ToggleFloor = 38,
    [pbr::OriginalName("TRAP_BUTTON")] TrapButton = 39,
    [pbr::OriginalName("TANK_BUTTON")] TankButton = 40,
    [pbr::OriginalName("TELEPORT")] Teleport = 41,
    [pbr::OriginalName("BOMB")] Bomb = 42,
    [pbr::OriginalName("TRAP")] Trap = 43,
    [pbr::OriginalName("INV_WALL_APP")] InvWallApp = 44,
    [pbr::OriginalName("GRAVEL")] Gravel = 45,
    [pbr::OriginalName("POP_UP_WALL")] PopUpWall = 46,
    [pbr::OriginalName("HINT")] Hint = 47,
    [pbr::OriginalName("PANEL_SE")] PanelSe = 48,
    [pbr::OriginalName("CLONER")] Cloner = 49,
    [pbr::OriginalName("FORCE_RANDOM")] ForceRandom = 50,
    [pbr::OriginalName("DROWN_CHIP")] DrownChip = 51,
    [pbr::OriginalName("BURNED_CHIP0")] BurnedChip0 = 52,
    [pbr::OriginalName("BURNED_CHIP1")] BurnedChip1 = 53,
    [pbr::OriginalName("NOT_USED_1")] NotUsed1 = 54,
    [pbr::OriginalName("NOT_USED_2")] NotUsed2 = 55,
    [pbr::OriginalName("NOT_USED_3")] NotUsed3 = 56,
    [pbr::OriginalName("CHIP_EXIT")] ChipExit = 57,
    [pbr::OriginalName("UNUSED_EXIT_0")] UnusedExit0 = 58,
    [pbr::OriginalName("UNUSED_EXIT_1")] UnusedExit1 = 59,
    [pbr::OriginalName("CHIP_SWIMMING_N")] ChipSwimmingN = 60,
    [pbr::OriginalName("CHIP_SWIMMING_W")] ChipSwimmingW = 61,
    [pbr::OriginalName("CHIP_SWIMMING_S")] ChipSwimmingS = 62,
    [pbr::OriginalName("CHIP_SWIMMING_E")] ChipSwimmingE = 63,
    [pbr::OriginalName("ANT_N")] AntN = 64,
    [pbr::OriginalName("ANT_W")] AntW = 65,
    [pbr::OriginalName("ANT_S")] AntS = 66,
    [pbr::OriginalName("ANT_E")] AntE = 67,
    [pbr::OriginalName("FIREBALL_N")] FireballN = 68,
    [pbr::OriginalName("FIREBALL_W")] FireballW = 69,
    [pbr::OriginalName("FIREBALL_S")] FireballS = 70,
    [pbr::OriginalName("FIREBALL_E")] FireballE = 71,
    [pbr::OriginalName("BALL_N")] BallN = 72,
    [pbr::OriginalName("BALL_W")] BallW = 73,
    [pbr::OriginalName("BALL_S")] BallS = 74,
    [pbr::OriginalName("BALL_E")] BallE = 75,
    [pbr::OriginalName("TANK_N")] TankN = 76,
    [pbr::OriginalName("TANK_W")] TankW = 77,
    [pbr::OriginalName("TANK_S")] TankS = 78,
    [pbr::OriginalName("TANK_E")] TankE = 79,
    [pbr::OriginalName("GLIDER_N")] GliderN = 80,
    [pbr::OriginalName("GLIDER_W")] GliderW = 81,
    [pbr::OriginalName("GLIDER_S")] GliderS = 82,
    [pbr::OriginalName("GLIDER_E")] GliderE = 83,
    [pbr::OriginalName("TEETH_N")] TeethN = 84,
    [pbr::OriginalName("TEETH_W")] TeethW = 85,
    [pbr::OriginalName("TEETH_S")] TeethS = 86,
    [pbr::OriginalName("TEETH_E")] TeethE = 87,
    [pbr::OriginalName("WALKER_N")] WalkerN = 88,
    [pbr::OriginalName("WALKER_W")] WalkerW = 89,
    [pbr::OriginalName("WALKER_S")] WalkerS = 90,
    [pbr::OriginalName("WALKER_E")] WalkerE = 91,
    [pbr::OriginalName("BLOB_N")] BlobN = 92,
    [pbr::OriginalName("BLOB_W")] BlobW = 93,
    [pbr::OriginalName("BLOB_S")] BlobS = 94,
    [pbr::OriginalName("BLOB_E")] BlobE = 95,
    [pbr::OriginalName("PARAMECIUM_N")] ParameciumN = 96,
    [pbr::OriginalName("PARAMECIUM_W")] ParameciumW = 97,
    [pbr::OriginalName("PARAMECIUM_S")] ParameciumS = 98,
    [pbr::OriginalName("PARAMECIUM_E")] ParameciumE = 99,
    [pbr::OriginalName("BLUE_KEY")] BlueKey = 100,
    [pbr::OriginalName("RED_KEY")] RedKey = 101,
    [pbr::OriginalName("GREEN_KEY")] GreenKey = 102,
    [pbr::OriginalName("YELLOW_KEY")] YellowKey = 103,
    [pbr::OriginalName("FLIPPERS")] Flippers = 104,
    [pbr::OriginalName("FIRE_BOOTS")] FireBoots = 105,
    [pbr::OriginalName("SKATES")] Skates = 106,
    [pbr::OriginalName("SUCTION_BOOTS")] SuctionBoots = 107,
    [pbr::OriginalName("PLAYER_N")] PlayerN = 108,
    [pbr::OriginalName("PLAYER_W")] PlayerW = 109,
    [pbr::OriginalName("PLAYER_S")] PlayerS = 110,
    [pbr::OriginalName("PLAYER_E")] PlayerE = 111,
  }

  #endregion

  #region Messages
  public sealed partial class Levelset : pb::IMessage<Levelset>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Levelset> _parser = new pb::MessageParser<Levelset>(() => new Levelset());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Levelset> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cc1LevelsetUtils.Cc1LevelsetReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Levelset() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Levelset(Levelset other) : this() {
      name_ = other.name_;
      levels_ = other.levels_.Clone();
      stories_ = other.stories_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Levelset Clone() {
      return new Levelset(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "levels" field.</summary>
    public const int LevelsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Cc1LevelsetUtils.Level> _repeated_levels_codec
        = pb::FieldCodec.ForMessage(18, global::Cc1LevelsetUtils.Level.Parser);
    private readonly pbc::RepeatedField<global::Cc1LevelsetUtils.Level> levels_ = new pbc::RepeatedField<global::Cc1LevelsetUtils.Level>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Cc1LevelsetUtils.Level> Levels {
      get { return levels_; }
    }

    /// <summary>Field number for the "stories" field.</summary>
    public const int StoriesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Cc1LevelsetUtils.Levelset.Types.Story> _repeated_stories_codec
        = pb::FieldCodec.ForMessage(26, global::Cc1LevelsetUtils.Levelset.Types.Story.Parser);
    private readonly pbc::RepeatedField<global::Cc1LevelsetUtils.Levelset.Types.Story> stories_ = new pbc::RepeatedField<global::Cc1LevelsetUtils.Levelset.Types.Story>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Cc1LevelsetUtils.Levelset.Types.Story> Stories {
      get { return stories_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Levelset);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Levelset other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if(!levels_.Equals(other.levels_)) return false;
      if(!stories_.Equals(other.stories_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      hash ^= levels_.GetHashCode();
      hash ^= stories_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      levels_.WriteTo(output, _repeated_levels_codec);
      stories_.WriteTo(output, _repeated_stories_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      levels_.WriteTo(ref output, _repeated_levels_codec);
      stories_.WriteTo(ref output, _repeated_stories_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      size += levels_.CalculateSize(_repeated_levels_codec);
      size += stories_.CalculateSize(_repeated_stories_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Levelset other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      levels_.Add(other.levels_);
      stories_.Add(other.stories_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            levels_.AddEntriesFrom(input, _repeated_levels_codec);
            break;
          }
          case 26: {
            stories_.AddEntriesFrom(input, _repeated_stories_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            levels_.AddEntriesFrom(ref input, _repeated_levels_codec);
            break;
          }
          case 26: {
            stories_.AddEntriesFrom(ref input, _repeated_stories_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Levelset message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class Story : pb::IMessage<Story>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Story> _parser = new pb::MessageParser<Story>(() => new Story());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Story> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Cc1LevelsetUtils.Levelset.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Story() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Story(Story other) : this() {
          levelNumber_ = other.levelNumber_;
          type_ = other.type_;
          text_ = other.text_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Story Clone() {
          return new Story(this);
        }

        /// <summary>Field number for the "level_number" field.</summary>
        public const int LevelNumberFieldNumber = 1;
        private int levelNumber_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int LevelNumber {
          get { return levelNumber_; }
          set {
            levelNumber_ = value;
          }
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 2;
        private global::Cc1LevelsetUtils.Levelset.Types.Story.Types.Type type_ = global::Cc1LevelsetUtils.Levelset.Types.Story.Types.Type.Prologue;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Cc1LevelsetUtils.Levelset.Types.Story.Types.Type Type {
          get { return type_; }
          set {
            type_ = value;
          }
        }

        /// <summary>Field number for the "text" field.</summary>
        public const int TextFieldNumber = 3;
        private static readonly pb::FieldCodec<string> _repeated_text_codec
            = pb::FieldCodec.ForString(26);
        private readonly pbc::RepeatedField<string> text_ = new pbc::RepeatedField<string>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<string> Text {
          get { return text_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Story);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Story other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (LevelNumber != other.LevelNumber) return false;
          if (Type != other.Type) return false;
          if(!text_.Equals(other.text_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (LevelNumber != 0) hash ^= LevelNumber.GetHashCode();
          if (Type != global::Cc1LevelsetUtils.Levelset.Types.Story.Types.Type.Prologue) hash ^= Type.GetHashCode();
          hash ^= text_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (LevelNumber != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(LevelNumber);
          }
          if (Type != global::Cc1LevelsetUtils.Levelset.Types.Story.Types.Type.Prologue) {
            output.WriteRawTag(16);
            output.WriteEnum((int) Type);
          }
          text_.WriteTo(output, _repeated_text_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (LevelNumber != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(LevelNumber);
          }
          if (Type != global::Cc1LevelsetUtils.Levelset.Types.Story.Types.Type.Prologue) {
            output.WriteRawTag(16);
            output.WriteEnum((int) Type);
          }
          text_.WriteTo(ref output, _repeated_text_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (LevelNumber != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(LevelNumber);
          }
          if (Type != global::Cc1LevelsetUtils.Levelset.Types.Story.Types.Type.Prologue) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
          }
          size += text_.CalculateSize(_repeated_text_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Story other) {
          if (other == null) {
            return;
          }
          if (other.LevelNumber != 0) {
            LevelNumber = other.LevelNumber;
          }
          if (other.Type != global::Cc1LevelsetUtils.Levelset.Types.Story.Types.Type.Prologue) {
            Type = other.Type;
          }
          text_.Add(other.text_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                LevelNumber = input.ReadInt32();
                break;
              }
              case 16: {
                Type = (global::Cc1LevelsetUtils.Levelset.Types.Story.Types.Type) input.ReadEnum();
                break;
              }
              case 26: {
                text_.AddEntriesFrom(input, _repeated_text_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                LevelNumber = input.ReadInt32();
                break;
              }
              case 16: {
                Type = (global::Cc1LevelsetUtils.Levelset.Types.Story.Types.Type) input.ReadEnum();
                break;
              }
              case 26: {
                text_.AddEntriesFrom(ref input, _repeated_text_codec);
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the Story message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          public enum Type {
            [pbr::OriginalName("PROLOGUE")] Prologue = 0,
            [pbr::OriginalName("EPILOGUE")] Epilogue = 1,
          }

        }
        #endregion

      }

    }
    #endregion

  }

  public sealed partial class Level : pb::IMessage<Level>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Level> _parser = new pb::MessageParser<Level>(() => new Level());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Level> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cc1LevelsetUtils.Cc1LevelsetReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Level() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Level(Level other) : this() {
      title_ = other.title_;
      author_ = other.author_;
      number_ = other.number_;
      time_ = other.time_;
      chips_ = other.chips_;
      hint_ = other.hint_;
      password_ = other.password_;
      map_ = other.map_.Clone();
      trapControls_ = other.trapControls_.Clone();
      cloneControls_ = other.cloneControls_.Clone();
      movement_ = other.movement_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Level Clone() {
      return new Level(this);
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 1;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "author" field.</summary>
    public const int AuthorFieldNumber = 2;
    private string author_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Author {
      get { return author_; }
      set {
        author_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "number" field.</summary>
    public const int NumberFieldNumber = 3;
    private int number_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Number {
      get { return number_; }
      set {
        number_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 4;
    private int time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "chips" field.</summary>
    public const int ChipsFieldNumber = 5;
    private int chips_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Chips {
      get { return chips_; }
      set {
        chips_ = value;
      }
    }

    /// <summary>Field number for the "hint" field.</summary>
    public const int HintFieldNumber = 6;
    private string hint_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Hint {
      get { return hint_; }
      set {
        hint_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 7;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "map" field.</summary>
    public const int MapFieldNumber = 8;
    private static readonly pbc::MapField<int, global::Cc1LevelsetUtils.TileSpec>.Codec _map_map_codec
        = new pbc::MapField<int, global::Cc1LevelsetUtils.TileSpec>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Cc1LevelsetUtils.TileSpec.Parser), 66);
    private readonly pbc::MapField<int, global::Cc1LevelsetUtils.TileSpec> map_ = new pbc::MapField<int, global::Cc1LevelsetUtils.TileSpec>();
    /// <summary>
    /// All int32 values must be packed and unpacked by these formulas:
    ///          p = y * 32 + x
    ///       x, y = p % 32, p // 32
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Cc1LevelsetUtils.TileSpec> Map {
      get { return map_; }
    }

    /// <summary>Field number for the "trap_controls" field.</summary>
    public const int TrapControlsFieldNumber = 9;
    private static readonly pbc::MapField<int, int>.Codec _map_trapControls_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt32(16, 0), 74);
    private readonly pbc::MapField<int, int> trapControls_ = new pbc::MapField<int, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, int> TrapControls {
      get { return trapControls_; }
    }

    /// <summary>Field number for the "clone_controls" field.</summary>
    public const int CloneControlsFieldNumber = 10;
    private static readonly pbc::MapField<int, int>.Codec _map_cloneControls_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt32(16, 0), 82);
    private readonly pbc::MapField<int, int> cloneControls_ = new pbc::MapField<int, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, int> CloneControls {
      get { return cloneControls_; }
    }

    /// <summary>Field number for the "movement" field.</summary>
    public const int MovementFieldNumber = 11;
    private static readonly pb::FieldCodec<int> _repeated_movement_codec
        = pb::FieldCodec.ForInt32(90);
    private readonly pbc::RepeatedField<int> movement_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Movement {
      get { return movement_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Level);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Level other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Title != other.Title) return false;
      if (Author != other.Author) return false;
      if (Number != other.Number) return false;
      if (Time != other.Time) return false;
      if (Chips != other.Chips) return false;
      if (Hint != other.Hint) return false;
      if (Password != other.Password) return false;
      if (!Map.Equals(other.Map)) return false;
      if (!TrapControls.Equals(other.TrapControls)) return false;
      if (!CloneControls.Equals(other.CloneControls)) return false;
      if(!movement_.Equals(other.movement_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (Author.Length != 0) hash ^= Author.GetHashCode();
      if (Number != 0) hash ^= Number.GetHashCode();
      if (Time != 0) hash ^= Time.GetHashCode();
      if (Chips != 0) hash ^= Chips.GetHashCode();
      if (Hint.Length != 0) hash ^= Hint.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      hash ^= Map.GetHashCode();
      hash ^= TrapControls.GetHashCode();
      hash ^= CloneControls.GetHashCode();
      hash ^= movement_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Title.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Title);
      }
      if (Author.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Author);
      }
      if (Number != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Number);
      }
      if (Time != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Time);
      }
      if (Chips != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Chips);
      }
      if (Hint.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Hint);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Password);
      }
      map_.WriteTo(output, _map_map_codec);
      trapControls_.WriteTo(output, _map_trapControls_codec);
      cloneControls_.WriteTo(output, _map_cloneControls_codec);
      movement_.WriteTo(output, _repeated_movement_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Title.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Title);
      }
      if (Author.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Author);
      }
      if (Number != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Number);
      }
      if (Time != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Time);
      }
      if (Chips != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Chips);
      }
      if (Hint.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Hint);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Password);
      }
      map_.WriteTo(ref output, _map_map_codec);
      trapControls_.WriteTo(ref output, _map_trapControls_codec);
      cloneControls_.WriteTo(ref output, _map_cloneControls_codec);
      movement_.WriteTo(ref output, _repeated_movement_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (Author.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Author);
      }
      if (Number != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Number);
      }
      if (Time != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Time);
      }
      if (Chips != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Chips);
      }
      if (Hint.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Hint);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      size += map_.CalculateSize(_map_map_codec);
      size += trapControls_.CalculateSize(_map_trapControls_codec);
      size += cloneControls_.CalculateSize(_map_cloneControls_codec);
      size += movement_.CalculateSize(_repeated_movement_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Level other) {
      if (other == null) {
        return;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.Author.Length != 0) {
        Author = other.Author;
      }
      if (other.Number != 0) {
        Number = other.Number;
      }
      if (other.Time != 0) {
        Time = other.Time;
      }
      if (other.Chips != 0) {
        Chips = other.Chips;
      }
      if (other.Hint.Length != 0) {
        Hint = other.Hint;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      map_.Add(other.map_);
      trapControls_.Add(other.trapControls_);
      cloneControls_.Add(other.cloneControls_);
      movement_.Add(other.movement_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Title = input.ReadString();
            break;
          }
          case 18: {
            Author = input.ReadString();
            break;
          }
          case 24: {
            Number = input.ReadInt32();
            break;
          }
          case 32: {
            Time = input.ReadInt32();
            break;
          }
          case 40: {
            Chips = input.ReadInt32();
            break;
          }
          case 50: {
            Hint = input.ReadString();
            break;
          }
          case 58: {
            Password = input.ReadString();
            break;
          }
          case 66: {
            map_.AddEntriesFrom(input, _map_map_codec);
            break;
          }
          case 74: {
            trapControls_.AddEntriesFrom(input, _map_trapControls_codec);
            break;
          }
          case 82: {
            cloneControls_.AddEntriesFrom(input, _map_cloneControls_codec);
            break;
          }
          case 90:
          case 88: {
            movement_.AddEntriesFrom(input, _repeated_movement_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Title = input.ReadString();
            break;
          }
          case 18: {
            Author = input.ReadString();
            break;
          }
          case 24: {
            Number = input.ReadInt32();
            break;
          }
          case 32: {
            Time = input.ReadInt32();
            break;
          }
          case 40: {
            Chips = input.ReadInt32();
            break;
          }
          case 50: {
            Hint = input.ReadString();
            break;
          }
          case 58: {
            Password = input.ReadString();
            break;
          }
          case 66: {
            map_.AddEntriesFrom(ref input, _map_map_codec);
            break;
          }
          case 74: {
            trapControls_.AddEntriesFrom(ref input, _map_trapControls_codec);
            break;
          }
          case 82: {
            cloneControls_.AddEntriesFrom(ref input, _map_cloneControls_codec);
            break;
          }
          case 90:
          case 88: {
            movement_.AddEntriesFrom(ref input, _repeated_movement_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TileSpec : pb::IMessage<TileSpec>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TileSpec> _parser = new pb::MessageParser<TileSpec>(() => new TileSpec());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TileSpec> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cc1LevelsetUtils.Cc1LevelsetReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TileSpec() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TileSpec(TileSpec other) : this() {
      top_ = other.top_;
      bottom_ = other.bottom_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TileSpec Clone() {
      return new TileSpec(this);
    }

    /// <summary>Field number for the "top" field.</summary>
    public const int TopFieldNumber = 1;
    private global::Cc1LevelsetUtils.CC1TileCode top_ = global::Cc1LevelsetUtils.CC1TileCode.Floor;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cc1LevelsetUtils.CC1TileCode Top {
      get { return top_; }
      set {
        top_ = value;
      }
    }

    /// <summary>Field number for the "bottom" field.</summary>
    public const int BottomFieldNumber = 2;
    private global::Cc1LevelsetUtils.CC1TileCode bottom_ = global::Cc1LevelsetUtils.CC1TileCode.Floor;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cc1LevelsetUtils.CC1TileCode Bottom {
      get { return bottom_; }
      set {
        bottom_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TileSpec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TileSpec other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Top != other.Top) return false;
      if (Bottom != other.Bottom) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Top != global::Cc1LevelsetUtils.CC1TileCode.Floor) hash ^= Top.GetHashCode();
      if (Bottom != global::Cc1LevelsetUtils.CC1TileCode.Floor) hash ^= Bottom.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Top != global::Cc1LevelsetUtils.CC1TileCode.Floor) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Top);
      }
      if (Bottom != global::Cc1LevelsetUtils.CC1TileCode.Floor) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Bottom);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Top != global::Cc1LevelsetUtils.CC1TileCode.Floor) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Top);
      }
      if (Bottom != global::Cc1LevelsetUtils.CC1TileCode.Floor) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Bottom);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Top != global::Cc1LevelsetUtils.CC1TileCode.Floor) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Top);
      }
      if (Bottom != global::Cc1LevelsetUtils.CC1TileCode.Floor) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Bottom);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TileSpec other) {
      if (other == null) {
        return;
      }
      if (other.Top != global::Cc1LevelsetUtils.CC1TileCode.Floor) {
        Top = other.Top;
      }
      if (other.Bottom != global::Cc1LevelsetUtils.CC1TileCode.Floor) {
        Bottom = other.Bottom;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Top = (global::Cc1LevelsetUtils.CC1TileCode) input.ReadEnum();
            break;
          }
          case 16: {
            Bottom = (global::Cc1LevelsetUtils.CC1TileCode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Top = (global::Cc1LevelsetUtils.CC1TileCode) input.ReadEnum();
            break;
          }
          case 16: {
            Bottom = (global::Cc1LevelsetUtils.CC1TileCode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
